# Fichier pour les overrides de développement local
# Ce fichier est automatiquement chargé par Docker Compose en développement
# Il surcharge les paramètres de compose.yaml pour le développement

services:
  php:
    # Les volumes sont déjà définis dans compose.yaml, mais on peut les ajuster ici si nécessaire
    # Les variables d'environnement sont déjà configurées dans compose.yaml avec des valeurs par défaut

###> doctrine/doctrine-bundle ###
  database:
    # Exposer le port PostgreSQL pour le développement local
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
